marlinprotocol/interface-v2

- src/lib/components/select/Select.svelte
- src/lib/page-components/oyster/OysterDashboard.svelte
- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/helpers/oysterHelpers.ts
- src/routes/oyster/+layout.svelte
- src/routes/oyster/marketplace/+page.svelte
1. In marketplace, create order, when cost is filled/updated, duration doesn't update
2. If cost is updated in create order popup, days should get auto populated
> Updating duration when cost is updated

- src/lib/page-components/oyster/inventory/modals/AddFundsToJobModal.svelte
- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- src/lib/page-components/oyster/sub-components/AddFundsToJob.svelte
- src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
- src/lib/utils/helpers/oysterHelpers.ts
- src/lib/utils/services/oysterServices.ts
1. In marketplace, create order, when cost is filled/updated, duration doesn't update
2. If cost is updated in create order popup, days should get auto populated
3. In add funds, it should be possible to set cost directly and days should be updated based on that
4. If large number is added to days in create order popup and then decreased, the cost field gets stuck at a fixed cost
> cost and duration conversion fixes

- src/lib/components/search/SearchWithSelect.svelte
- src/lib/controllers/contractController.ts
- src/lib/controllers/subgraphController.ts
- src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
- src/lib/page-components/oyster/inventory/modals/AddFundsToJobModal.svelte
- src/lib/page-components/oyster/inventory/modals/AmendRateModal.svelte
- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
- src/lib/page-components/oyster/inventory/modals/PastJobDetailsModal.svelte
- src/lib/page-components/oyster/inventory/modals/StopJobModal.svelte
- src/lib/page-components/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplaceTableRow.svelte
- src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
- src/lib/types/oysterComponentType.ts
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/constants/subgraphQueries.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
- src/lib/utils/helpers/oysterHelpers.ts
1. Change modal deploy button design as per Shabbir's suggestion
2. Remove guide  link from My active orders page
3. Job Id to be  change to Job as per  changes in subgraph
4. When a rate change is initiated, there is no marker to let me know that it is
5. improvement: disable create modal select when no data, replacing modal subtitle with lorem ipsum
> rate subgraph changes

- src/lib/controllers/contractController.ts
- src/lib/controllers/subgraphController.ts
- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
- src/lib/page-components/oyster/inventory/modals/AmendRateModal.svelte
- src/lib/page-components/oyster/inventory/modals/StopJobModal.svelte
- src/lib/page-components/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
- src/lib/page-components/oyster/sub-components/StopModalContent.svelte
- src/lib/types/oysterComponentType.ts
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
- src/lib/utils/services/oysterServices.ts
1. Update data locally on revise rate request based on current subgraph changes
2. There should be a timer which runs when rate change is initiated
3. Link job id when creating new order
> rate revise fixes

- src/lib/controllers/httpController.ts
- src/lib/controllers/subgraphController.ts
- src/routes/+layout.svelte
- src/routes/+layout.ts
- src/routes/bridge/+layout.svelte
- src/routes/bridge/+layout.ts
- src/routes/oyster/+layout.svelte
- src/routes/oyster/+layout.ts
Using the load function gives us a significant performance boost in our load times and page loading. Following are some metrics that were taken from deploying the app on our server.
|Page|Finish|DOMContentLoaded|Load|
|----|------|:--------------:|----|
|Bridge|5.38s|287ms|4.61s|
|Staking|5.37s|266ms|5.45s|
|Marketplace|6.46s|290ms|5.35s|
|Page|Finish|DOMContentLoaded|Load|
|----|------|:--------------:|----|
|Bridge|5.15s|261ms|4.28s|
|Staking|5.15s|271ms|4.27s|
|Marketplace|5.62s|288ms|5.07s|
> PR for using sveltekit load function for loading initial page data for all routes

- src/lib/components/header/sub-components/ChainSwitcher.svelte
- src/lib/controllers/contract/receiverRewards.ts
- src/lib/controllers/contract/receiverStaking.ts
- src/lib/page-components/bridge/MPondTopond.svelte
- src/lib/page-components/bridge/history/MPondTableRow.svelte
- src/lib/page-components/bridge/history/PondToMPondHistoryData.svelte
- src/lib/page-components/bridge/modals/MPondConversionCycleModal.svelte
- src/lib/page-components/bridge/modals/MPondConversionHistoryModal.svelte
- src/lib/page-components/bridge/modals/MPondEligibleConvertModal.svelte
- src/lib/page-components/bridge/modals/SuccessfulConversionModal.svelte
- src/lib/page-components/oyster/inventory/modals/PastJobDetailsModal.svelte
- src/lib/page-components/receiver-rewards/modals/AddRewardBalanceModal.svelte
- src/lib/page-components/receiver-rewards/modals/InitiateRewardModal.svelte
- src/lib/page-components/receiver-rewards/modals/UpdateTicketRewardsModal.svelte
- src/lib/page-components/receiver-staking/UnstakeModal.svelte
- src/lib/utils/helpers/conversionHelper.ts
- add functionality to close the chain switcher component when the user clicks outside
- remove `bigNumberToCommaString` with `bigNumberToString` which is a more robust and readable function (will raise another PR to rename this function better sometime later)
- add reset functions to receiver reward modals
> PR to remove TODOs and minor updates

- src/lib/components/header/sub-components/DisconnectWalletModal.svelte
- src/lib/components/texts/TextInputCard.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
- src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
- src/lib/utils/helpers/componentHelper.ts
- add copy icon in inventory table row and job detail modal
- create a common function handler for copy to clipboard behaviour
> PR to add copy to clipboard functionality for IP address

- src/lib/atoms/tooltips/Tooltip.svelte
- src/lib/components/select/Select.svelte
- src/lib/components/texts/NameWithAddress.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplaceFilters.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplaceTableRow.svelte
- src/lib/types/oysterComponentType.ts
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
- src/lib/utils/helpers/oysterHelpers.ts
This PR fixes bugs in the oyster marketplace page related to row sizing, filtering and sorting, along with addition of a filter for arch type
> PR to fix oyster bugs and add filter for arch in marketplace

- src/lib/data-stores/oysterStore.ts
- src/lib/types/oysterComponentType.ts
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
> PR to fix metadata json.parse crash page loading

- src/lib/chains/arbGoerli.ts
- src/lib/chains/arbOne.ts
- src/lib/chains/linea.ts
- src/lib/chains/lineaGoerli.ts
- src/lib/components/header/sub-components/ChainSwitcher.svelte
- src/lib/components/header/sub-components/HeaderConnectWallet.svelte
- src/lib/controllers/walletController.ts
- src/lib/data-stores/chainProviderStore.ts
- src/lib/types/environmentTypes.ts
- src/lib/types/storeTypes.ts
- src/lib/utils/constants/storeDefaults.ts
- src/lib/utils/helpers/networkHelper.test.ts
- src/lib/utils/helpers/networkHelper.ts
Refactor two functions namely getChainDisplayName and getChainImage to getChainInfo
> Refactor Chain Config

- src/lib/chains/arbGoerli.ts
- src/lib/chains/arbOne.ts
- src/lib/chains/arbSepolia.ts
- src/lib/chains/linea.ts
- src/lib/chains/lineaGoerli.ts
- src/lib/components/header/sub-components/DisconnectWalletModal.svelte
- src/lib/components/images/staticImages.ts
- src/lib/components/prompts/AddTokenPrompt.svelte
- src/lib/data-stores/chainProviderStore.ts
- src/lib/page-components/receiver-staking/Test.svelte
- src/lib/types/environmentTypes.ts
- src/routes/test/+page.svelte
> PR to add token in user wallet watch list EIP 747 "wallet_watchAsset"

- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- test/e2e/walletConected/credits.spec.ts
- test/helpers/credits.ts
> Credits testing

- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- src/lib/page-components/oyster/inventory/modals/JobDetailsModal.svelte
- src/lib/page-components/oyster/inventory/modals/PastJobDetailsModal.svelte
- src/lib/types/oysterComponentType.ts
- src/lib/utils/constants/oysterConstants.ts
- src/lib/utils/data-modifiers/oysterModifiers.ts
- src/lib/utils/helpers/oysterHelpers.ts
This PR does the following:
- adds in a input for additional field called enclave input
- adds entry to job details modal
- adds entry to past job details modal
> PR to add in an input for additional enclave inputs during job creation

- src/lib/atoms/texts/Text.svelte
- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- test/e2e/walletConected/credits.spec.ts
- test/helpers/credits.ts
Using Id instead of class for getting current credits.
> Credits testing : minor bug fix

- src/lib/chains/arbGoerli.ts
- test/e2e/walletConected/chain.spec.ts
- test/e2e/walletConected/deployAJob.spec.ts
> Tests chain

- src/lib/components/v2/wrapper/PageWrapper.dom.spec.ts
- src/lib/components/v2/wrapper/PageWrapper.svelte
- src/lib/components/v2/wrapper/__snapshots__/PageWrapper.dom.spec.ts.snap
- src/routes/v2/+error.svelte
- src/routes/v2/bridge/+layout.svelte
- src/routes/v2/oyster/+layout.svelte
- src/routes/v2/relay/+layout.svelte
Added layout changes for keeping the page components in center and responsive w.r.t sidebar.
Ref:
https://github.com/marlinprotocol/interface-v2/assets/47270995/3446f44b-a8e4-4af3-a5ea-aad699d6e37
> Layout for v2

- src/lib/atoms/v2/componentClasses.ts
- src/lib/atoms/v2/modals/ModalButton.svelte
- src/lib/components/images/staticImages.ts
- src/lib/components/v2/search/SearchBar.svelte
- src/lib/page-components/v2/oyster/inventory/OysterInventoryPage.svelte
- src/lib/page-components/v2/oyster/inventory/OysterInventoryTableRow.svelte
- src/lib/page-components/v2/oyster/marketplace/OysterMarketplaceTableRow.svelte
- src/lib/types/v2/componentTypes.ts
- src/lib/utils/constants/v2/oysterConstants.ts
- src/lib/utils/constants/v2/urls.ts
- src/lib/utils/v2/helpers/componentHelper.ts
- src/lib/utils/v2/helpers/oysterHelpers.ts
- static/images/refreshV2Icon.svg
- static/images/searchV2Icon.svg
Improvements in UI as per latest figma design
> chore: added inventory ui improvement

- src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
> PR to add margin around sidebar gray box and linear gradient around scrollable nav

- src/lib/components/v2/header/sub-components/MenuItem.svelte
- src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
- src/lib/types/v2/navigation.ts
- src/lib/utils/constants/v2/navigation.ts
- src/lib/utils/constants/v2/urls.ts
> PR to update sidebar nav links 

- src/lib/atoms/v2/table/Table.svelte
- src/lib/page-components/v2/oyster/inventory/OysterTableCommon.svelte
- src/lib/page-components/v2/oyster/operator/OysterOperatorJobs.svelte
- src/lib/page-components/v2/oyster/operator/OysterOperatorJobsHistory.svelte
- src/lib/page-components/v2/oyster/operator/OysterOperatorRegisterPage.svelte
> Operator bug fixes

- src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
- src/lib/utils/constants/v2/navigation.ts
- src/lib/utils/constants/v2/urls.ts
- update the discord invite link and minor refactoring
- reorder sidebar menu items
- add a specific click behavior when user clicks on sidebar when in collapsed state
- minor fix for link navigation
> PR to add in fixes and updates to sidebar behaviour

- src/lib/atoms/v2/modals/ModalButton.svelte
- src/lib/components/v2/header/sub-components/SidebarLinksGroup.svelte
- src/lib/page-components/v2/dashboard/MarlinHubDashboard.svelte
- src/lib/types/v2/componentTypes.ts
- src/routes/v2/dashboard/+page.svelte
- src/routes/v2/oyster/+page.ts
> PR to add in the main dashboard

- src/lib/page-components/v2/oyster/inventory/OysterInventoryPage.svelte
- src/lib/page-components/v2/oyster/inventory/modals/WithdrawFundsFromJobModal.svelte
- add background while hovering to complete row in inventory
- fix undefined being shown up in withdraw modal
> PR to add bugfixes for new UI

- src/lib/page-components/v2/oyster/operator/OysterOperatorRegisterPage.svelte
- src/lib/utils/constants/v2/urls.ts
> fix: added documentation button in operator route

- src/lib/atoms/v2/modals/Modal.svelte
- src/lib/page-components/v2/oyster/inventory/modals/CreateOrderModal.svelte
- src/lib/page-components/v2/oyster/sub-components/BandwidthSelector.svelte
> Doc related fixes

- src/lib/components/images/staticImages.ts
- src/lib/page-components/oyster/operator/OysterOperatorJobsTableRow.svelte
- static/images/rightarrowwhite.svg
> fix: claim button icon

- src/lib/page-components/oyster/dashboard/OysterDashboardPage.svelte
> PR to update dashboard links and metadata

- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
> fix: enclave input ui

- src/lib/atoms/table/Table.svelte
- src/lib/components/texts/NameWithAddress.svelte
- src/lib/components/texts/TableHeadingText.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplaceTableRow.svelte
- src/lib/utils/constants/oysterConstants.ts
> fix: table center as per prop.

- src/lib/utils/constants/oysterConstants.ts
> fix: ip text upper case

- src/lib/components/header/sub-components/SidebarLinksGroup.svelte
- src/lib/page-components/dashboard/MarlinHubDashboard.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
- src/lib/page-components/oyster/sub-components/PaymentHistoryTable.svelte
- src/lib/types/componentTypes.ts
- src/lib/types/headerTypes.ts
- src/lib/utils/constants/constants.ts
> hub and oyster bugfixes

- src/lib/page-components/oyster/inventory/OysterInventoryHistoryTableRow.svelte
- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
> Address fix: Longer Address appear in Inventory and Past order page.

- src/lib/page-components/oyster/inventory/OysterInventoryTableRow.svelte
> bug-fix: credit job should have credit icon appear after credit number.

- src/lib/page-components/oyster/operator/OysterOperatorJobsTableRow.svelte
> removed extra dollar from accrued column in operator jobs

- src/lib/page-components/dashboard/MarlinHubDashboard.svelte
Navigation fix for navigation from marlin hub dashboard
> fix navigation

- src/lib/components/header/sub-components/ChainSwitcher.svelte
- src/lib/components/header/sub-components/ConnectWalletButton.svelte
- src/lib/components/header/sub-components/HeaderConnectWallet.svelte
- src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
- src/lib/components/prompts/NetworkPrompt.svelte
- src/lib/components/prompts/Prompts.dom.spec.ts
- src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
- src/lib/components/texts/PageTitle.svelte
- src/lib/page-components/bridge/history/HistoryTableCommon.svelte
- src/lib/page-components/bridge/history/MPondToPondHistoryData.svelte
- src/lib/page-components/bridge/history/PondToMPondHistoryData.svelte
- src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
- src/routes/bridge/+layout.svelte
- src/routes/oyster/+layout.svelte
Switch Button in Conversion Table
> Chain switcher dropdown

- src/lib/page-components/bridge/history/HistoryTableCommon.svelte
> fix: animation and icon change

- src/lib/components/modals/__snapshots__/ApproveAndConfirmModal.dom.spec.ts.snap
- src/lib/components/modals/__snapshots__/Modal.dom.spec.ts.snap
- src/lib/page-components/bridge/modals/SuccessfulConversionModal.svelte
> text wrap for conversion modal.

- src/lib/components/header/sub-components/DisconnectWalletButton.svelte
- src/lib/components/header/sub-components/__snapshots__/DisconnectWalletButton.dom.spec.ts.snap
- src/lib/components/header/sub-components/__snapshots__/HeaderConnectWallet.dom.spec.ts.snap
- test/e2e/walletConected/claim.spec.ts
- test/e2e/walletConected/operatorRegistration.spec.ts
- test/e2e/walletNotConnected/marketplace.spec.ts
- test/helpers/common.ts
> Fix/integration tests: Operator Registration, Unregistration, Update Flow & Claim Job Reward

- src/lib/components/search/SearchWithSelect.svelte
- src/lib/page-components/oyster/sub-components/MetadetailsForNewOrder.svelte
> create order modal disable first 3 inputs

- src/lib/page-components/oyster/sub-components/BandwidthSelector.svelte
https://github.com/marlinprotocol/interface-v2/assets/47270995/c59d8f55-19b2-4f84-9ed7-265014abee8a
> Create order modal cost fix

- src/lib/components/prompts/NetworkPrompt.svelte
- src/lib/components/prompts/__snapshots__/Prompts.dom.spec.ts.snap
- src/lib/page-components/oyster/sub-components/BandwidthSelector.svelte
- test/e2e/walletConected/common.spec.ts
- test/e2e/walletConected/deployAJob.spec.ts
- test/e2e/walletConected/inventory.spec.ts
- test/helpers/credits.ts
> Added Tests for bug-fixes 

- src/lib/page-components/oyster/marketplace/OysterMarketplaceFilters.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
- src/lib/utils/helpers/oysterHelper.test.ts
- src/lib/utils/helpers/oysterHelpers.ts
> oyster market place update

- src/lib/components/header/sub-components/ChainSwitcher.svelte
- src/lib/page-components/oyster/marketplace/OysterMarketplacePage.svelte
- src/routes/oyster/+layout.svelte
> fix: some reported bug

- src/lib/atoms/cards/ContainerCard.svelte
- src/lib/page-components/kalypso/KalypsoDashboard.svelte
- src/lib/page-components/kalypso/RegisteredOverview.svelte
- src/lib/page-components/kalypso/modals/KalypsoRegisterModal.svelte
- src/lib/page-components/kalypso/modals/UpdateRewardAddModal.svelte
> feat: overview UI

- src/lib/atoms/toast/Toast.svelte
- src/lib/data-stores/toastStore.ts
https://github.com/marlinprotocol/interface-v2/assets/58814221/3eaf151e-85f5-4c9d-a604-00fa4814f508
> move toasts to bottom right and updated their animation

- src/lib/controllers/subgraphController.ts
- src/lib/data-stores/oysterStore.ts
- src/lib/page-components/oyster/inventory/modals/CreateOrderModal.svelte
- src/routes/oyster/+layout.svelte
> fix showing credit toggle when wallet not whitelisted

- src/lib/components/texts/TextInputCard.svelte
- src/lib/components/texts/__snapshots__/Texts.dom.spec.ts.snap
- src/lib/page-components/oyster/inventory/OysterInventoryPage.svelte
https://www.loom.com/share/3cf13239885c472ab230de5cb1f76e95?sid=3986cae7-894d-42e8-a4b9-3a02b135eb5a
> fixed ui bugs

- src/lib/components/prompts/NetworkPrompt.svelte
- src/lib/page-components/kalypso/DashboardHeader.svelte
- src/lib/page-components/kalypso/ManageCompute.svelte
- src/lib/page-components/kalypso/ManageStake.svelte
- src/lib/page-components/kalypso/RegisteredOverview.svelte
- src/lib/page-components/oyster/inventory/OysterTableCommon.svelte
- tailwind.config.cjs
Before: 
After: 
Before: 
After:
> squashed UI bugs.

- src/lib/atoms/ThemeSwitcher.svelte
- src/lib/components/header/sub-components/SidebarLinksGroup.svelte
- src/lib/components/sidebar/Sidebar.svelte
> refactored and updated the theme switcher

- src/lib/components/texts/TextInputCard.svelte
https://github.com/user-attachments/assets/1ec8abdc-9d36-4be1-9a18-0b77cad91cd3
> on scroll inside text, fix copy button size
